parent_dir = '/Users/david/Box Sync/behavioral/data/';
input_dirs = {...
    'S153',...
    ...'S154',... % sub didn't do intermediate mem test
    'S255',...
    'S156',...
    'S157',...
    'S158',...
    'S159',...
    'S160',...
    'S161',...
    };

output_dir =...
    '/Users/david/OneDrive/Documents/Yale/NTB_lab/batters_problem/vma_recall_repo';

for i_dir = 1:length(input_dirs)
    [s, err] = combine_data_from_runs(...
        [parent_dir, filesep, input_dirs{i_dir}, filesep],...
        output_dir);
end
